import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Html,
  Img,
  Link,
  Preview,
  Section,
  Text,
} from '@react-email/components';
import * as React from 'react';

interface AnalysisResult {
  text: string;
  aiProbability: number;
  isAiGenerated: boolean;
  analysisId: string;
}

interface AnalysisCompleteEmailProps {
  userName: string;
  analysisResult: AnalysisResult;
}

export const AnalysisCompleteEmail = ({ userName, analysisResult }: AnalysisCompleteEmailProps) => {
  const { aiProbability, isAiGenerated, analysisId, text } = analysisResult;
  const dashboardUrl = `${process.env.NEXT_PUBLIC_BASE_URL || 'https://truecheckia.com'}/dashboard/analysis/${analysisId}`;
  const textPreview = text.length > 150 ? `${text.substring(0, 150)}...` : text;
  
  const resultColor = isAiGenerated ? '#dc2626' : '#16a34a';
  const resultText = isAiGenerated 
    ? 'Content likely generated by AI' 
    : 'Content likely written by humans';

  return (
    <Html>
      <Head />
      <Preview>Your TrueCheckIA analysis is complete - {`${Math.round(aiProbability)}%`} AI probability</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section style={logoContainer}>
            <Img
              src="https://truecheckia.com/logo.png"
              width="120"
              height="36"
              alt="TrueCheckIA"
              style={logo}
            />
          </Section>
          
          <Heading style={h1}>Analysis Complete!</Heading>
          
          <Text style={textStyle}>Hello {userName},</Text>
          
          <Text style={textStyle}>
            Your content analysis has been successfully processed. Here are the results:
          </Text>
          
          <Section style={resultBox}>
            <Text style={resultTitle}>Analysis Result</Text>
            <Text style={{...resultStatus, color: resultColor}}>
              {resultText}
            </Text>
            <Text style={probabilityText}>
              AI Probability: <strong>{Math.round(aiProbability)}%</strong>
            </Text>
          </Section>
          
          <Section style={contentBox}>
            <Text style={contentTitle}>Analyzed text:</Text>
            <Text style={contentPreview}>
              &quot;{textPreview}&quot;
            </Text>
          </Section>
          
          <Section style={buttonContainer}>
            <Button style={button} href={dashboardUrl}>
              View Full Analysis
            </Button>
          </Section>
          
          <Section style={insightBox}>
            <Text style={insightTitle}>💡 How to interpret the result</Text>
            <Text style={insightText}>
              {isAiGenerated ? (
                'A result above 50% indicates that the text was likely generated by artificial intelligence. ' +
                'The higher the percentage, the greater the confidence in detection.'
              ) : (
                'A result below 50% indicates that the text was likely written by a human. ' +
                'The lower the percentage, the greater the confidence that it is human content.'
              )}
            </Text>
          </Section>
          
          <Text style={textStyle}>
            You can access the complete analysis report in your dashboard. 
            There you will find more details and can download the result.
          </Text>
          
          <Text style={textStyle}>
            Thank you for using TrueCheckIA!
          </Text>
          
          <Section style={footer}>
            <Text style={footerText}>
              TrueCheckIA - Cutting-edge AI detection technology
            </Text>
            <Text style={footerLinks}>
              <Link href="https://truecheckia.com/privacy" style={link}>
                Privacy Policy
              </Link>
              {' | '}
              <Link href="https://truecheckia.com/terms" style={link}>
                Terms of Service
              </Link>
              {' | '}
              <Link href="https://truecheckia.com/contact" style={link}>
                Contact
              </Link>
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

export default AnalysisCompleteEmail;

// Styles
const main = {
  backgroundColor: '#f6f9fc',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
};

const logoContainer = {
  padding: '32px 20px',
  textAlign: 'center' as const,
};

const logo = {
  margin: '0 auto',
};

const h1 = {
  color: '#333',
  fontSize: '24px',
  fontWeight: 'bold',
  margin: '40px 0',
  padding: '0 20px',
  textAlign: 'center' as const,
};

const textStyle = {
  color: '#333',
  fontSize: '16px',
  lineHeight: '26px',
  margin: '16px 0',
  padding: '0 20px',
};

const resultBox = {
  backgroundColor: '#f8fafc',
  border: '2px solid #e2e8f0',
  borderRadius: '8px',
  margin: '24px 20px',
  padding: '20px',
  textAlign: 'center' as const,
};

const resultTitle = {
  color: '#334155',
  fontSize: '18px',
  fontWeight: 'bold',
  margin: '0 0 12px 0',
};

const resultStatus = {
  fontSize: '20px',
  fontWeight: 'bold',
  margin: '8px 0',
};

const probabilityText = {
  color: '#475569',
  fontSize: '16px',
  margin: '8px 0 0 0',
};

const contentBox = {
  backgroundColor: '#f9fafb',
  border: '1px solid #e5e7eb',
  borderRadius: '6px',
  margin: '24px 20px',
  padding: '16px',
};

const contentTitle = {
  color: '#374151',
  fontSize: '14px',
  fontWeight: 'bold',
  margin: '0 0 8px 0',
};

const contentPreview = {
  color: '#6b7280',
  fontSize: '14px',
  fontStyle: 'italic',
  lineHeight: '20px',
  margin: '0',
};

const insightBox = {
  backgroundColor: '#fef7cd',
  border: '1px solid #f59e0b',
  borderRadius: '6px',
  margin: '24px 20px',
  padding: '16px',
};

const insightTitle = {
  color: '#92400e',
  fontSize: '16px',
  fontWeight: 'bold',
  margin: '0 0 8px 0',
};

const insightText = {
  color: '#92400e',
  fontSize: '14px',
  lineHeight: '20px',
  margin: '0',
};

const buttonContainer = {
  textAlign: 'center' as const,
  margin: '32px 0',
};

const button = {
  backgroundColor: '#3b82f6',
  borderRadius: '6px',
  color: '#fff',
  fontSize: '16px',
  fontWeight: 'bold',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '12px 24px',
};

const footer = {
  borderTop: '1px solid #eaeaea',
  marginTop: '32px',
  padding: '20px',
  textAlign: 'center' as const,
};

const footerText = {
  color: '#666',
  fontSize: '14px',
  lineHeight: '24px',
  margin: '0',
};

const footerLinks = {
  color: '#666',
  fontSize: '14px',
  lineHeight: '24px',
  margin: '8px 0 0',
};

const link = {
  color: '#3b82f6',
  textDecoration: 'underline',
};